import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';

// Render exact synthetic message text as a phone UI, avoiding AI-generated text errors.
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#111;font-family:-apple-system,BlinkMacSystemFont,Arial,sans-serif}.status{height:54px;display:flex;justify-content:space-between;align-items:center;padding:0 26px;font-size:15px;font-weight:600}.status-right{display:flex;align-items:center;gap:6px}.bars{display:flex;align-items:flex-end;gap:2px}.bars i{width:3px;background:#111;border-radius:1px;height:6px}.bars i:nth-child(2){height:9px}.bars i:nth-child(3){height:12px}.bars i:nth-child(4){height:15px}.battery{border:1px solid #111;border-radius:4px;width:24px;height:12px;padding:1px}.battery span{display:block;width:90%;height:100%;background:#111;border-radius:2px}.header{height:101px;border-bottom:1px solid #dedede;background:#fafafa;position:relative;text-align:center;padding-top:5px}.back{position:absolute;left:18px;top:33px;width:13px;height:13px;border-left:3px solid #157aff;border-bottom:3px solid #157aff;transform:rotate(45deg)}.avatar{height:49px;width:49px;border-radius:50%;background:#b7bbc2;display:flex;align-items:center;justify-content:center;margin:0 auto 7px;color:#fff;font-size:24px}.avatar svg{height:34px;width:34px}.sender{font-size:12px}.date{text-align:center;font-size:11px;color:#919196;margin:23px 0 5px}.sms{text-align:center;font-size:10px;color:#aaaab0;margin-bottom:24px}.bubble{background:#e9e9eb;border-radius:19px;padding:14px 16px;max-width:298px;margin-left:17px;font-size:16px;line-height:1.38;position:relative;letter-spacing:-.25px}.bubble:before{content:'';position:absolute;bottom:0;left:-6px;width:17px;height:20px;border-radius:0 0 14px 0;background:#e9e9eb}.url{color:#111;text-decoration:none;overflow-wrap:anywhere}.footer{position:absolute;bottom:0;left:0;width:100%;background:#fff;padding:15px 15px 22px}.compose{display:flex;gap:13px;align-items:center;color:#a2a2a7}.plus{font-size:29px;font-weight:200}.input{height:36px;flex:1;border:1px solid #d8d8da;border-radius:19px;color:#a8a8ad;display:flex;align-items:center;padding:0 13px;font-size:15px}.home{height:5px;width:135px;background:#111;border-radius:5px;margin:20px auto -10px}.note{position:absolute;left:0;right:0;bottom:145px;text-align:center;color:#b4b4b8;font-size:9px;letter-spacing:.5px}
</style></head><body><div class="status"><span>9:41</span><div class="status-right"><div class="bars"><i></i><i></i><i></i><i></i></div><span style="font-size:11px">5G</span><span class="battery"><span></span></span></div></div><div class="header"><span class="back"></span><div class="avatar"><svg viewBox="0 0 40 40"><circle cx="20" cy="13" r="7" fill="white"/><path d="M7 35c0-17 26-17 26 0" fill="white"/></svg></div><div class="sender">+1 (202) 555-0147</div></div><div class="date">Today 9:38 AM</div><div class="sms">Text Message · SMS</div><div class="bubble">UPS: We could not deliver your package. Pay the $1.99 redelivery fee within 12 hours to avoid return: <span class="url">https://ups-redelivery-fee.example/pay</span></div><div class="note">SYNTHETIC MESSAGE · HARBOR DEMO</div><div class="footer"><div class="compose"><span class="plus">+</span><div class="input">Text Message</div></div><div class="home"></div></div></body></html>`);
mkdirSync('public/demo', { recursive: true });
await page.screenshot({ path: 'public/demo/ups-message.png' });
await browser.close();
console.log('Rendered public/demo/ups-message.png');
